### ISSUE TITLE
data-invalid remains when validation rules are removed from the input

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#1384]
### Reproduction

https://formkit.link/8078c60918386346316fbc4f74d332a8

### Describe the bug

When a validation rule is conditionally removed (reboot validation) the `failing` state is not reset.

### Environment

• OS: macOS
• Browser: Chrome
• Version: 1.6.4

**Comment by justin-schroeder** [comment]
fixed in 1.6.5

**Comment by Nobe-san** [comment]
@justin-schroeder problem is still on textarea, its permanently as data-complete true.

**Comment by justin-schroeder** [comment]
@Nobe-san I dont think there is a bug here, but feel free to demonstrate with a reproduction and ill take a look. The complete state is described here: https://formkit.com/api-reference/context#state

```js
{
  ...
  /**
   * True when these conditions are met:
   *
   * Either:
   * - The input has validation rules
   * - The validation rules are all passing
   * - There are no errors on the input
   * Or:
   * - The input has no validation rules
   * - The input has no errors
   * - The input is dirty and has a value
   *
   * This is not intended to be used on forms/groups/lists, but instead on
   * individual inputs. Imagine placing a green checkbox next to each input
   * when the user filled it out correctly — that's what these are for.
   */
  complete: boolean,
  ...
}
```
