### ISSUE TITLE
Not updating select options in latest release

### ISSUE THREAD

**Issue by jurjenvn** [formkit/formkit#191]
### Reproduction

https://formkit.link/9c8bbf2856444b9301c7963527f75647

### Describe the bug

When trying to update the options of a select the select disappears on the latest Beta 6 release. On Beta 4 however the options do get updated correctly. Setting an initial value for the constant formdata.treatments does break things though, but that may be a separate issue.  

### Environment

This issue appears on the Beta 6 release, while on Beta 4 it seems to work correctly.

**Comment by justin-schroeder** [comment]
Thanks @jurjenvn. I *think* this is already fixed in beta.7 (the `@next` tag) here is your playground using beta 7:

https://formkit.link/1428223eb8bc6035ac7eec2644f29801

You can install this version today by installing `@formkit/vue@next`. If I missed something about your issue thats not working in beta 7 feel free to reopen this 👍

**Comment by kdekooter** [comment]
@justin-schroeder I am afraid it is still not working in beta 12
