### ISSUE TITLE
[Vue warn] Maximum recursive updates exceeded in component <FormKitSchema>

### ISSUE THREAD

**Issue by NgaNguyenDuy** [formkit/formkit#225]
### Reproduction

https://formkit.link/1567a16d96ea8d820c0775a94cd4f133

### Describe the bug

Vue warn a message on browser console when using validation by array syntax

### Environment

• OS: macOS
• Browser: Safari, Firefox
• Version: Firefox (99), Safari (15.4)

**Comment by justin-schroeder** [comment]
Fixed and deployed on the `@next` tag. If you do a hard refresh on your code example this should now be fixed 👍

**Comment by pommedepain** [comment]
@justin-schroeder Not fixed for me with the @next tag ! I had to define a computed with my string validation to escape the issue 😞 

Here how it was defined at first:
`<form-kit
	type="date-picker"
	enable-time-picker
	placeholder="Select a date"
	label="arrival date *"
	name="assignDate"
	:min-date="new Date()"
	:validation="`required|date_after:${luxon.DateTime.now()}`"
/>`

Here how it is now:
`
const datePickerValidation = computed(() => `required|date_after:${luxon.DateTime.now()}`);

<form-kit
	type="date-picker"
	enable-time-picker
	placeholder="Select a date"
	label="arrival date *"
	name="assignDate"
	:min-date="new Date()"
	:validation="datePickerValidation"
/>`

**Comment by justin-schroeder** [comment]
well, the previous bug was fixed with the date tag, you might have found a new one. Are you able to create a reproduction in the playground?
