### ISSUE TITLE
[0.17.2] Input blur event cause "Cannot read properties of null (reading 'store')"

### ISSUE THREAD

**Issue by parafeu** [formkit/formkit#735]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-mbv6sq?file=src%2Fpages%2FForm2.vue

### Describe the bug

When leaving a page with a Formkit input focused (using browser navigation to avoid blur before leaving), the blur event occur but the node is already destroyed and it throw this error :

![image](https://github.com/formkit/formkit/assets/39409783/42e42342-3df9-4269-b25e-3666bf23b13b)

This issue is likely due to the absence of verification for the existence of the node in this code.

![image](https://github.com/formkit/formkit/assets/39409783/f6dbb316-b6e4-4587-92f9-0958aa65fcd5)

### Environment

• OS: MacOS Ventura (Apple Silicon), Debian 11
• Browser: Chrome
• Version: 113

**Comment by darthf1** [comment]
I'm having the same issue.

![image](https://github.com/formkit/formkit/assets/17253332/d75ea6ce-2827-4afb-a380-0c30403c2c71)

**Comment by darthf1** [comment]
@GustavoFenilli I'm using Ubuntu 23.04 with MS Edge 114.0.1823.37. According to Sentry, this also happens for Windows uers

**Comment by frasza** [comment]
I have created reproduction in Nuxt App -> https://github.com/frasza/formkit-bug

**Comment by mudassirmaqbool** [comment]
Same issue. I was able to fix by downgrading to v0.16.0. Bugs show up in  0.17.0+

**Comment by davidAtInleague** [comment]
I got a Sentry log come in this morning, bringing me here. We recently bumped all our Formkit deps to `^0.17.2`.

```
TypeError: Cannot read properties of null (reading 'store')
    at Proxy.blur (<<approot>>/app/assets/app.c99793ce.js:15:109812) //@formkit/vue/dist/index.mjs:1600:21
    at al (<<approot>>/app/assets/app.c99793ce.js:1:13809)
    at xi (<<approot>>/app/assets/app.c99793ce.js:1:13888)
    at HTMLInputElement.n (<<approot>>/app/assets/app.c99793ce.js:1:60356)
```

Browser appears to be Edge115, based on Sentry's reading of user agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.7`

**Comment by gekkota** [comment]
+1 for this issue.

 Resolved temporary by using these. 
    "@formkit/themes": "^0.16.5",
    "@formkit/vue": "^0.16.4",

**Comment by gbyesiltas** [comment]
Same here ✋

versions we're using:
```
    "@formkit/addons": "0.17.2",
    "@formkit/i18n": "0.17.2",
    "@formkit/nuxt": "0.17.2",
    "@formkit/pro": "0.112.5",
```

**Comment by parafeu** [comment]
Hello ! 

I tried to update to v0.17.3, and I'm still having the issue. 
I suppose it's because you are checking if node is `undefined`, but on this issue the node is `null`.

**Comment by CavalcanteLeo** [comment]
same issue here...

it happens when I close a modal that has focus on the input
