### ISSUE TITLE
Cannot unselect item by clicking on it in autoselect options dropdown after it has been focused in input

### ISSUE THREAD

**Issue by radusuciu** [formkit/formkit#946]
### Reproduction

https://formkit.link/358dd9b835e497dc78e58fb662f453bc

### Describe the bug

Behavior is a little difficult to explain, but I've captured it in this gif. It's perhaps a little worse when combined with `open-on-click` since you're likely to focus on one of the items in the input.

Normal behavior. Clicking on a selected item unselects it.
![GIF 2023-09-13 6-21-14 PM](https://github.com/formkit/formkit/assets/1108600/4b1871f1-f7a4-4361-b9be-507b7e813bad)

Buggy behavior. If you focus on an item in the input, you can no longer unselect by clicking on it in the options dropdown.
![GIF 2023-09-13 6-21-51 PM](https://github.com/formkit/formkit/assets/1108600/640a9845-cc78-4ff9-85c3-e9270e0aa790)

### Environment

• OS: Windows 10
• Browser: Edge
• Version: latest

**Comment by sashamilenkovic** [comment]
@radusuciu This has been addressed at 0.115.6 of @formkit/pro. Let me know if that resolves the issue for you.

**Comment by radusuciu** [comment]
Does not seem resolved on the playground but perhaps that is behind a version still?

I still see a separate, but perhaps related, issue in my project but I cannot replicate it on the playground.. the node labels seem to get out of sync with the values when toggling items while another item has focus in the input.

**Comment by sashamilenkovic** [comment]
@radusuciu It's very possible the playground is not pulling the latest dependency. Have you tried installing 0.115.6 in your local dev?

**Comment by radusuciu** [comment]
> @radusuciu It's very possible the playground is not pulling the latest dependency. Have you tried installing 0.115.6 in your local dev?

Yes, I have and have verified the appropriate `package.json` file as well. I am attempting a playground reproduction of the potentially separate issue I mentioned, but so far have been unable to get it done. The only other customizations I've applied are to the `classes` attribute to add some bootstrap utility classes..

**Comment by radusuciu** [comment]
@sashamilenkovic, the issue referenced in the title is no longer happening locally, or on the playground.

**Comment by radusuciu** [comment]
Also, I no longer see the other issue I mentioned above. Thanks again!
